provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: ap-southeast-2

custom:
  stage: "${opt:stage, self:provider.stage}"

service: iot-button-hpc

functions:
  startHPC:
    handler: invoke.handler
    events:
      - iot:
          sql: "SELECT * FROM '${file(env.yml):${self:custom.stage}.START_BUTTON}'"
    environment: ${file(env.yml):${self:custom.stage}}
    RoleARN:
      Fn::GetAtt: [ lambda-cloudformation, Arn ]

  stopHPC:
    handler: delete.handler
    events:
      - iot:
          sql: "SELECT * FROM '${file(env.yml):${self:custom.stage}.STOP_BUTTON}'"
    RoleARN:
      Fn::GetAtt: [ lambda-cloudformation, Arn ]
