provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: ap-southeast-2
  role: 'arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/lambda-cloudformation'

service: iot-button-hpc

functions:
  stopstartHPC:
    handler: handlers.press
    events:
      - iot:
          sql: "SELECT * FROM '${env:BUTTON}'"
    environment:
      NOTIFICATION_ARN: ${env:NOTIFICATION_ARN}
      ACCESS_KEY_NAME: ${env:ACCESS_KEY_NAME}
      ACCESS_NETWORK: ${env:ACCESS_NETWORK}
      TEMPLATE_URL: ${env:TEMPLATE_URL}
