provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: ap-southeast-2
  role: 'arn:aws:iam::${file(env.yml):${self:custom.stage}.AWS_ACCOUNT_ID}:role/lambda-cloudformation'

custom:
  stage: "${opt:stage, self:provider.stage}"

service: iot-button-hpc

functions:
  startHPC:
    handler: handlers.invoke
    events:
      - iot:
          sql: "SELECT * FROM '${file(env.yml):${self:custom.stage}.START_BUTTON}'"
    environment: ${file(env.yml):${self:custom.stage}}

  stopHPC:
    handler: handlers.delete
    events:
      - iot:
          sql: "SELECT * FROM '${file(env.yml):${self:custom.stage}.STOP_BUTTON}'"
